@startuml
title "Регистрация (детальная)"
actor user
boundary "DeviceUser" as device
boundary "MobileApp" as mobapp
entity "DB MobileApp" as dbmob
control "BACK" as back
entity "DB BACK" as db
control "FAPI" as fapi

        user -> mobapp : вводНомераТелефона
        activate mobapp
            mobapp -> back : request: sendRegisterCode (mobilePhone)
            activate back
                back -> fapi : request: front_new/registration/init (mobilePhone)
                activate fapi
                    fapi --> back : response: front_new/registration/init (status, operationId)
                deactivate fapi
                back -> fapi : request: front_new/registration/otp/send (operationId)
                activate fapi
                    fapi --> back : response: front_new/registration/otp/send (status, data)
                deactivate fapi
                alt ошибка отправки кода (status != 1)
                    back --> mobapp : errorSending
                    mobapp --> user : ошибка отправки кода
                else код успешно отправлен (status = 1)
                    back --> mobapp : successSending
                    mobapp -> mobapp : switchScreen
                    mobapp --> user : отправлено смс с кодом подтверждения
                end
            deactivate back
        deactivate mobapp
        ...клиент ожидает смс...
            opt клиент ожидает смс более 1-й минуты
                loop
                ...клиент ожидает смс...
                    user -> mobapp : инициализация повторной отправки смс
                    activate mobapp
                        mobapp -> back : sendRegisterCode
                        activate back
                            back -> fapi : POST front_new/registration/init
                            activate fapi
                                fapi --> back : response  front_new/registration/init
                            deactivate fapi
                            back -> fapi : POST front_new/registration/otp/send
                            activate fapi
                                fapi --> back : response  front_new/registration/otp/send
                            deactivate fapi
                            back --> mobapp : smsSended
                        deactivate back
                        mobapp --> user : отправлено повторное смс\nс кодом подтверждения
                    deactivate mobapp
                end
            end
        ...клиент ожидает смс...
        user -> mobapp : ввод кода подтверждения
        activate mobapp
            mobapp -> back : checkRegisterCode
            activate back
                back -> fapi : POST /front_new/registration/otp/validate
                activate fapi
                    fapi --> back : response  /front_new/registration/otp/validate
                deactivate fapi
                alt ошибка проверки кода
                    back --> mobapp : errorCheck
                    mobapp --> user : ошибка проверки кода [расшифровка ошибки]
                else код успешно проверен
                    back --> mobapp : successCheck
                end
            deactivate back
            mobapp ->> dbmob : saveMobilePhone [временное сохранение моб. номера пользователя]
            mobapp -> mobapp : switchScreen [ввод пароля для входа]
            mobapp --> user : Введите новый пароль для входа
        deactivate mobapp
            ...ожидание ввода нового пароля...
            user -> mobapp : Ввод 4-х значного пароля
            activate mobapp
                mobapp ->> dbmob : saveCode [временное сохранение введённого пароля]
                mobapp -> mobapp : switchScreen [подтверждение пароля для входа]
                mobapp --> user : введите пароль повторно
            deactivate mobapp
            ...ожидание повторного ввода нового пароля...
            alt failure checkCode [пароль не совпадает с введённым раннее]
                loop
                    user -> mobapp : повторный ввод пароля
                    activate mobapp
                        mobapp -> mobapp : checkCode [сравнение пароля с введённым раннее]
                        mobapp --> user : пароль не совпадает с введённым раннее
                end
            else success checkCode [пароль совпадает с введённым раннее]
                mobapp -> back : createUser (phoneNumber, code, [deviceInfo])
                activate back
                    back -> db : createUser (userId, phoneNumber, code, [deviceInfo])
                    activate db
                        db --> back : success createUser (userId)
                    deactivate db
                    back --> mobapp : success createUser (userId)
                deactivate back
                    mobapp ->> dbmob : saveUserId [долговременное сохранение идентификатора пользователя]
                    mobapp ->> dbmob : deleteMobilePhone [удаление из памяти номера телефона пользователя]
                    mobapp -> mobapp : switchScreen [запрос на отпечаток пальца]
                    mobapp -> device : fingerprint access
                deactivate mobapp
                activate device
                    device -> user : access fingerprint?
                    alt access: false
                    user --> device : access: false
                    device --> mobapp : access: false
                    activate mobapp
                    mobapp -> mobapp :  switchScreen [запрос на faceid]
                    else access: true
                    user --> device : access: true
                    device --> mobapp : access: true
                deactivate device
                    mobapp ->> dbmob : createUserAuth (userId, fingerprint: true) [долговременное сохранение способа авторизации]
                    mobapp -> back : createUserAuth (userId, fingerprint: true)
                    activate back
                        back -> db : createUserAuth (userId, fingerprint: true)
                        activate db
                            db --> back : success
                        deactivate db
                        back --> mobapp : success
                    deactivate back
                    mobapp -> mobapp :  switchScreen [запрос на faceid]
                    end
                    mobapp -> device : faceid access
                deactivate mobapp
                activate device
                    device -> user : access faceid?
                    alt access: false
                    user --> device : access: false
                    device --> mobapp : access: false
                    activate mobapp
                    mobapp -> mobapp :  switchScreen [ввод данных по адресу],/nпроцесс регистрации завершён
                    else access: true
                    user --> device : access: true
                    device --> mobapp : access: true
                deactivate device
                    mobapp ->> dbmob : createUserAuth (userId, faceid: true) [долговременное сохранение способа авторизации]
                    mobapp -> back : createUserAuth (userId, faceid: true)
                    activate back
                        back -> db : createUserAuth (userId, faceid: true)
                        activate db
                            db --> back : success
                        deactivate db
                        back --> mobapp : success
                    deactivate back
                    mobapp -> mobapp :  switchScreen [ввод данных по адресу],/nпроцесс регистрации завершён
                    end
                    deactivate mobapp
            end

@enduml
