@startuml
title "Регистрация"
actor user
boundary "DeviceUser" as device
boundary "MobileApp" as mobapp
entity "DB MobileApp" as dbmob
control "BACK" as back
entity "DB BACK" as db
control "FAPI" as fapi

        user -> mobapp : Получение номера телефона клиента
        activate mobapp
            mobapp ->> dbmob : request: saveTimedInfo (mobilePhone) [временное сохранение моб. номера пользователя]
            mobapp -> back : request: sendRegisterCode (mobilePhone)
            activate back
                back -> db : request: checkUser (mobilePhone)
                activate db
                    db --> back : response: checkUser (result, mobilePhone, userId)
                deactivate db
alt пользователя нет в базе (checkUser (result=0))
                back -> fapi : request: front_new/registration/init (mobilePhone)
                activate fapi
                    fapi --> back : response: front_new/registration/init (status, operationId)
                deactivate fapi
                back ->> db : request: saveTimedInfo (operationId, mobilePhone) [временное сохранение связки]
                back -> fapi : request: front_new/registration/otp/send (operationId)
                activate fapi
                    fapi --> back : response: front_new/registration/otp/send (status, data)
                deactivate fapi
                    back --> mobapp : response: sendRegisterCode (success)
                    mobapp -> mobapp : switchScreen
                    mobapp --> user : отправлено смс с кодом подтверждения
            deactivate back
        deactivate mobapp
        ...клиент ожидает смс...
        user -> mobapp : ввод кода подтверждения
        activate mobapp
            mobapp -> back : request: checkRegisterCode (code, mobilePhone)
            activate back
                back -> db : request: checkInfo (mobilePhone)
                activate db
                    db --> back : response: checkInfo (mobilePhone, operationId)
                deactivate db
                back -> fapi : request: front_new/registration/otp/validate (code, operationId)
                activate fapi
                    fapi --> back : response: front_new/registration/otp/validate (status, data)
                deactivate fapi
                    back --> mobapp : response: checkRegisterCode (success)
            deactivate back
            mobapp -> mobapp : switchScreen [ввод пароля для входа]
            mobapp --> user : Введите новый пароль для входа
        deactivate mobapp
            ...ожидание ввода нового пароля...
            user -> mobapp : Ввод 4-х значного пароля
            activate mobapp
                mobapp ->> dbmob : request: saveTimedInfo (code) [временное сохранение введённого пароля]
                mobapp -> mobapp : switchScreen [подтверждение пароля для входа]
                mobapp --> user : введите пароль повторно
            deactivate mobapp
            ...ожидание повторного ввода нового пароля...
                    user -> mobapp : повторный ввод пароля
                    activate mobapp
                        mobapp -> mobapp : checkCode [сравнение пароля с введённым раннее]
                mobapp ->> dbmob : request: deleteTimedInfo (code) [удаление из памяти временных данных]
                mobapp -> back : request: createUser (mobilePhone, code)
                activate back
                    back -> db : request: createUser (userId, mobilePhone, code)
                    activate db
                        db --> back : response: createUser (status, userId)
                    deactivate db
                    back --> mobapp : response: createUser (status, userId)
                deactivate back
                    mobapp ->> dbmob : request: saveInfo (userId) [долговременное сохранение идентификатора пользователя]
                    mobapp ->> dbmob : request: deleteTimedInfo (mobilePhone) [удаление из памяти временных данных]
                    mobapp -> mobapp : switchScreen [запрос на отпечаток пальца]
                    mobapp -> device : fingerprint access
                deactivate mobapp
                activate device
                    device -> user : access fingerprint?
                    user --> device : access: true
                    device --> mobapp : access: true
                                    deactivate device
                    activate mobapp

                    mobapp -> device : faceid access
                deactivate mobapp
                activate device
                    device -> user : access faceid?
                    user --> device : access: true
                    device --> mobapp : access: true
                deactivate device
                activate mobapp
                    mobapp -> mobapp :  switchScreen [ввод данных по адресу],\nпроцесс регистрации завершён
else пользователь есть в базе (checkUser (result=1))
activate back
back --> mobapp : response: sendRegisterCode (user to authorization)
deactivate back
mobapp -> mobapp :  switchScreen [переход на авторизацию],\nпроцесс регистрации не потребовался
                        deactivate mobapp
end
@enduml
