@startuml
title "Общий процесс оплаты по СБП"
actor user
boundary "FRONT" as front
control "FAPI" as fapi
control "SBP Service" as sbp
control "M+ Sys" as sys

user -> front : "Оплатить"
activate front
    front -> fapi : checkSBP
    activate fapi
        fapi -> sbp : request /v1/qrc/check:\npayment_recipient_id: +
        activate sbp
            sbp --> fapi : response /v1/qrc/check:\n{"code": 0,\n"message": "string",\n"data": true}
        deactivate sbp
        fapi --> front : checkSBP: true
    deactivate fapi
    front --> user : Отображение способов оплаты (включая СБП)
deactivate front

user -> front : Выбор клиентом СБП
activate front
    front -> fapi : getQr
    activate fapi
        fapi -> sys : ??? (transaction_id) [ запись платежа в БД с временным статусом ожидания\nдля "бронирования" transaction_id.\nПлатёж СБП не нужно проводить в банке или иных системах]
        activate sys
            sys --> fapi : result  (transaction_id)
        deactivate sys
        fapi -> sbp : request /v1/qrc:\n{\n"transaction_id": -\n"user_id":[ain] +\n"payment_recipient_id": +\n"invoice_number": +/-\n"personal_account_number": +/-\n"amount": +\n}
        activate sbp
            sbp --> fapi : response  /v1/qrc: {\n"code": 0,\n"message": "string",\n"data": {\n"data": {\n"qrc_id": "string",\n"payload": "string",\n"image": "string"\n},\n"code": "string",\n"message": "string"\n}\n}\n
        deactivate sbp
        fapi --> front : getQr: image, payload, qrc_id
    deactivate fapi
    front -> front : сохранение информации о qrc_id
    front --> user : Отображение QR-кода

loop крутим ожидание
    front -> front : Ожидание

...может быть опущено, в случае обновления статуса транзакции напрямую из СБП...

loop опрос на результат оплаты СБП, пока не получим checkSBPPay: true
    front -> fapi : checkSBPPay: qrc_id
    activate fapi
        fapi -> sbp : request /v1/qrc/{qrc_id}
        activate sbp
            sbp --> fapi : response  /v1/qrc/{qrc_id}: {\n"code": 0,\n"message": "string",\n"data": {\n"data": {\n"operation_id": "string",\n"status": "string",\n"reason": "string"\n},\n"code": "string",\n"message": "string"\n}\n}\n
        deactivate sbp
        fapi --> front : checkSBPPay: status
    deactivate fapi
end

    front -> fapi : sbpPay: transactionId, qrc_id
    activate fapi
        fapi -> sys : запись платежа в БД и проведение его в системе.\nПлатёж СБП не нужно проводить в банке или иных системах.\nПлатёж отправляется сюда в случае, если он уже списан со счёта клиента.
        activate sys
            sys --> fapi : платёж на проведении
        deactivate sys
        fapi --> front : платёж на проведении
    deactivate fapi

...может быть опущено, в случае обновления статуса транзакции напрямую из СБП...

loop опрос на результат оплаты М+, пока не получим result: "1", "0", "5", "2", "6"
    front -> fapi : get_transaction_result_by_id.do
    activate fapi
        fapi -> sys : получение результата транзакции
        activate sys

alt траназакция успешна
            sys --> fapi : успех
        fapi --> front : успех
else траназакция неуспешна, рефанд, НУЖНО ПОДРОБНЕЕ ПРОДУМАТЬ ПРОЦЕСС РЕФАНДА
            sys --> fapi : неуспех
        deactivate sys
        fapi ->> front : неуспех
        fapi -> sbp : refundSBP
        activate sbp
            sbp --> fapi : refund: in progress
        deactivate sbp
    deactivate fapi
end

end

end

    front --> user : Отображение результата транзакции
deactivate front

@enduml
