@startuml
title "Добавление Поставщика к адресу"
actor user
boundary "MobileApp" as mobapp
entity "DB MobileApp" as dbmob
control "BACK" as back
entity "DB BACK" as db
control "A3 API" as a3
' сделать альтернативу с вводом данных в полях из выпадающего списка при нажатии на отдельного Поставщика

user -> mobapp : переход на добавление отдельного Поставщика
activate mobapp
    mobapp -> mobapp : switchScreen [отображение необходимых полей\nввода по Поставщику listProviders/providerId\nиз listProviders/providerId/params]
    'mobapp -> back : getProviderParams (listProviders/providerId)\n[Получение необходимых полей\nдля данного Поставщика]
    mobapp --> user : введите данные
deactivate mobapp

...ожидание ввода данных...
user ->>  mobapp : Ввод данных
user -> mobapp : Нажатие "Далее"
activate mobapp
    mobapp -> back : searchInProvider(providerId, param1, param2...) [поиск введённых данных]
    activate back
        back -> a3 : searchInProvider(providerId, param1, param2...) [поиск введённых данных]
alt Данные не найдены
        a3 --> back : result NotFound
        back --> mobapp : result NotFound
        mobapp --> user : Данные не найдены [индикация]
'else Необходимо уточнение (доввод данных)
'        a3 --> back : result needMoreInfo (providerId, param1, param2...)
'        back --> mobapp : result needMoreInfo (providerId, param1, param2...)
'        mobapp -> mobapp : switchScreen [отображение дополнительных полей ввода для идентификации клиента]
'        mobapp --> user : введите дополнительные данные
'
'        ...ожидание ввода данных...
'
'        user ->>  mobapp : Ввод дополнительных данных
'        user -> mobapp : Нажатие "Далее"
else Данные найдены
         a3 --> back : result searchSuccess (providerId, info, invoice...)
         back -> db : addNewProvider (addressId, providerId, params, info...)
         activate db
            db --> back : result success
         deactivate db
         back --> mobapp : result searchSuccess (providerId, info, invoice...)
         mobapp -> mobapp : switchScreen [отображение экрана оплаты]
         mobapp --> user : Оплатить, добавить дополнительного Поставщика\nили перейти на дашборд [завершение добавления Поставщика к адресу]
end
    deactivate back
deactivate mobapp

@enduml
